# General Settings
seed: 42
batch_size: 256
secret_batch_size: 4
num_epochs: 10
contrastive_loss_weight: 0.1
margin: 35

# Model Configuration
model:
  name: "facebook/opt-30b"
  input_dim: 7168
  output_dim: 128
  secret_dim: 48
  num_layers: 4
  num_heads: 16
  dropout: 0.2
  hidden_dim: 1024

# Y-Model Configuration
y_model:
  path: "./models/Ymodel.pth"
  sentence_encode_model_name: "sentence-transformers/all-mpnet-base-v2"
  sentence_encode_dim: 768
  output_range_max: 1

# Optimizer and Scheduler Settings
learning_rate: 0.0003
warmup_steps: 1000
weight_decay: 0.01

# Dataset Configuration
dataset_path: "./dataset/hidden_states_0_15_L48_facebook_opt-30b.h5"
test_split_ratio: 0.1
num_workers: 1